### ISSUE TITLE
Support for serialized columns?

### ISSUE THREAD

**Issue by rmosolgo** [taskrabbit/demoji#4]
Thanks so much for your work on this! 

We have some serialized columns that could use emoji-stripping. Are you interested in supporting that use case? If so, maybe we can cook up a PR.

**Comment by davidjairala** [comment]
Hey sorry for the slow reply,  missed this issue somehow,  my bad. 

I'd be very interested in supporting it and would appreciate a PR.   Thanks!

**Comment by rmosolgo** [comment]
Eh, it looks like the API for detecting serialized columns will change in Rails 5:

https://github.com/rails/rails/blob/b3bfa361c503e107aff4dee5edf79bd7fd3d3725/activerecord/lib/active_record/attribute_methods/serialization.rb#L55

Rather than try to shim something in that will probably break in the future, I implemented a `NoEmojiJSON` coder in my app:

```ruby
class NoEmojiJSON
  # source: http://stackoverflow.com/a/24674266/1741654
  EMOJI_PATTERN = /[\u{1F600}-\u{1F6FF}]/
  def self.load(json_string)
    JSON.load(json_string)
  end

  def self.dump(object)
    json_string = JSON.dump(object)
    json_string.gsub(EMOJI_PATTERN, ' ')
  end
end
```

Then used it in the model:

```ruby
  serialize :session_data, NoEmojiJSON
```

Thanks for your help!
